export default Object.freeze({
  HTTP_STATUS_UNAUTHORIZED: 401,
  HTTP_STATUS_FORBIDDEN: 403,
  HTTP_STATUS_UNPROCESSABLE_ENTITY: 422,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
  VUEX_PERSISTED_STATE_KEY: 'notenext-state',
  MAX_SIZE_KB_UPLOAD_IMAGE_FILE: 8192,
  MAX_LENGTH_TEXT: 32768,
});
